name: Release
on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # QEMU
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      # Buildx
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v1
      # Docker login
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_PAT }}
      # dotnet core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.102
      # Semantic release
      - name: Get version tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@master
      # Simplified Semantic release version
      - name: SemVer
        id: semver
        run: |
          SEMVER=${{ steps.previoustag.outputs.tag }}
          RELEASE_VERSION="${SEMVER:1}"
          echo ::set-output name=RELEASE_VERSION::${RELEASE_VERSION}
      # Login, build & publish docker image
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Trove.Api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/trove:latest
            ghcr.io/${{ github.repository_owner }}/trove:${{ steps.semver.outputs.RELEASE_VERSION }}
          build-args: RELEASE_VERSION=${{ steps.semver.outputs.RELEASE_VERSION }}
          platforms: linux/amd64,linux/arm/v7